spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/railway
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: none